core:
  worker_num: 1024
  queue_num: 8192
  fail_fast_timeout: 3 # 当程序收到signal时候，要保证在fail_fast_timeout(unit: second)时间段内退出
  pid:
    enabled: false
    path: "kafka2es.pid"
    override: true

kafka:
  brokers: "10.33.80.155:9092,10.33.80.170:9092,10.33.80.171:9092"
  topic: "bc_log"
  consumer_group: "bc"

es:
  es_hosts:
    -
      http://10.33.80.170:9200
  shard_num: 5
  replica_num: 0
  refresh_interval: 300

  index: bc
  index_time_suffix_format: -%d%02d%02d
  type: go
  kibana_time_filed: timestamp
  kibana_time_format: yyyyMMdd HH:mm:ss.SSSZ
  bulk_size: 5000
  bulk_timeout: 60